{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.firebasemessaging",
    "module": "firebase_messaging_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.core",
          "module": "firebase_core_release",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "firebase_messaging_release-1.0.aar",
          "url": "firebase_messaging_release-1.0.aar",
          "size": 49015,
          "sha512": "5512a144d55405be5952d2711379b587200f5a01be680cd24fab2c5c7bcfb56fb86f2f4c521be6eeb81088cb2d3d1481e29f87b8e561d3595bf08c1be0b4a87c",
          "sha256": "de9994b07d2869f91bded531f422f8f30cb68d8dee03b0e88bef89fa5681152c",
          "sha1": "bca28a5fa09926e974c91216b4c846f7ca53fe57",
          "md5": "b699ea7da6dc7e3c55aa97632316916d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-bom",
          "version": {
            "requires": "32.6.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-messaging"
        },
        {
          "group": "androidx.localbroadcastmanager",
          "module": "localbroadcastmanager",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-iid",
          "version": {
            "requires": "21.1.0"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.core",
          "module": "firebase_core_release",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "firebase_messaging_release-1.0.aar",
          "url": "firebase_messaging_release-1.0.aar",
          "size": 49015,
          "sha512": "5512a144d55405be5952d2711379b587200f5a01be680cd24fab2c5c7bcfb56fb86f2f4c521be6eeb81088cb2d3d1481e29f87b8e561d3595bf08c1be0b4a87c",
          "sha256": "de9994b07d2869f91bded531f422f8f30cb68d8dee03b0e88bef89fa5681152c",
          "sha1": "bca28a5fa09926e974c91216b4c846f7ca53fe57",
          "md5": "b699ea7da6dc7e3c55aa97632316916d"
        }
      ]
    }
  ]
}
