{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.pharsh.sms_user_consent",
    "module": "sms_user_consent_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        }
      ],
      "files": [
        {
          "name": "sms_user_consent_release-1.0.aar",
          "url": "sms_user_consent_release-1.0.aar",
          "size": 9903,
          "sha512": "8cc2c6816fe07f71dc3db5ced4911cc11e01297015e51455f6cc4e8b6c5305cd323c5058c60b49155488e86b4fe3ce56aa1f17f89618f0be62058da6cfbb7484",
          "sha256": "43ef7dce3b1695da7dfde18e4e615fead2d02a5c4ca876ad6e97845814cdcf6d",
          "sha1": "b7260a4f5ff6943e14a8610f8c120dadb328f4d0",
          "md5": "e482218fe31565733eef388c25892d30"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.3.50"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-auth",
          "version": {
            "requires": "18.1.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-auth-api-phone",
          "version": {
            "requires": "17.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "sms_user_consent_release-1.0.aar",
          "url": "sms_user_consent_release-1.0.aar",
          "size": 9903,
          "sha512": "8cc2c6816fe07f71dc3db5ced4911cc11e01297015e51455f6cc4e8b6c5305cd323c5058c60b49155488e86b4fe3ce56aa1f17f89618f0be62058da6cfbb7484",
          "sha256": "43ef7dce3b1695da7dfde18e4e615fead2d02a5c4ca876ad6e97845814cdcf6d",
          "sha1": "b7260a4f5ff6943e14a8610f8c120dadb328f4d0",
          "md5": "e482218fe31565733eef388c25892d30"
        }
      ]
    }
  ]
}
