{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.pharsh.sms_user_consent",
    "module": "sms_user_consent_profile",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        }
      ],
      "files": [
        {
          "name": "sms_user_consent_profile-1.0.aar",
          "url": "sms_user_consent_profile-1.0.aar",
          "size": 9906,
          "sha512": "6487eb57147e135501f854bab3813311998c61ee6bce99a797fd74eeaebae434a720d61ccf7940d9e3f96644c7d7a4c2cf134d3c1b2e91c61700672351ae38dc",
          "sha256": "2dbc78189013981db7e8e64a7ff08a7d1aab0831920bbee4bbc59eaaa040ad97",
          "sha1": "95e6936952931239c96267545569cd2a293f6f79",
          "md5": "e93d5ad416570302681de319d4938eb1"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.3.50"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-auth",
          "version": {
            "requires": "18.1.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-auth-api-phone",
          "version": {
            "requires": "17.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "sms_user_consent_profile-1.0.aar",
          "url": "sms_user_consent_profile-1.0.aar",
          "size": 9906,
          "sha512": "6487eb57147e135501f854bab3813311998c61ee6bce99a797fd74eeaebae434a720d61ccf7940d9e3f96644c7d7a4c2cf134d3c1b2e91c61700672351ae38dc",
          "sha256": "2dbc78189013981db7e8e64a7ff08a7d1aab0831920bbee4bbc59eaaa040ad97",
          "sha1": "95e6936952931239c96267545569cd2a293f6f79",
          "md5": "e93d5ad416570302681de319d4938eb1"
        }
      ]
    }
  ]
}
