{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.firebasemessaging",
    "module": "firebase_messaging_profile",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.core",
          "module": "firebase_core_profile",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "firebase_messaging_profile-1.0.aar",
          "url": "firebase_messaging_profile-1.0.aar",
          "size": 49022,
          "sha512": "79237253f06a5c26bc84f38c155dab7c1e905a511ee3d2fe3e93d0cec44e19162adb84a7f12d92e467c669dce96f3da2f253c352582c849a9e950dc79b8b037a",
          "sha256": "1c2325e54e937dfbd21988f4bc1a0795d0af7dc4f257b18a5980871c6a5ebb30",
          "sha1": "0a01e29f69322505d69086d083d30a4d02ceef7e",
          "md5": "f7d0151015e94c56b64f7990d71f9f36"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-bom",
          "version": {
            "requires": "32.6.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-messaging"
        },
        {
          "group": "androidx.localbroadcastmanager",
          "module": "localbroadcastmanager",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-iid",
          "version": {
            "requires": "21.1.0"
          }
        },
        {
          "group": "io.flutter.plugins.firebase.core",
          "module": "firebase_core_profile",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "firebase_messaging_profile-1.0.aar",
          "url": "firebase_messaging_profile-1.0.aar",
          "size": 49022,
          "sha512": "79237253f06a5c26bc84f38c155dab7c1e905a511ee3d2fe3e93d0cec44e19162adb84a7f12d92e467c669dce96f3da2f253c352582c849a9e950dc79b8b037a",
          "sha256": "1c2325e54e937dfbd21988f4bc1a0795d0af7dc4f257b18a5980871c6a5ebb30",
          "sha1": "0a01e29f69322505d69086d083d30a4d02ceef7e",
          "md5": "f7d0151015e94c56b64f7990d71f9f36"
        }
      ]
    }
  ]
}
