{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.pharsh.sms_user_consent",
    "module": "sms_user_consent_debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        }
      ],
      "files": [
        {
          "name": "sms_user_consent_debug-1.0.aar",
          "url": "sms_user_consent_debug-1.0.aar",
          "size": 10278,
          "sha512": "ff8ab5b7d172afef04e7829f68c99a5090e99547b85eb6f01c858dcc2a4bc159e663926ff4205c9df2171f7668969a531c87418c43629464d18f9f06a24c4ddc",
          "sha256": "2b8316c57a06b46035cce54769b1f6583760bcbd11c8de13b737121e26ad3893",
          "sha1": "4ba94fff14ad38ba8d8ecd6a4c78224a7d110c11",
          "md5": "6652e664def0387116615654770bf1c8"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-ec975089acb540fc60752606a3d3ba809dd1528b"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.3.50"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-auth",
          "version": {
            "requires": "18.1.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-auth-api-phone",
          "version": {
            "requires": "17.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "sms_user_consent_debug-1.0.aar",
          "url": "sms_user_consent_debug-1.0.aar",
          "size": 10278,
          "sha512": "ff8ab5b7d172afef04e7829f68c99a5090e99547b85eb6f01c858dcc2a4bc159e663926ff4205c9df2171f7668969a531c87418c43629464d18f9f06a24c4ddc",
          "sha256": "2b8316c57a06b46035cce54769b1f6583760bcbd11c8de13b737121e26ad3893",
          "sha1": "4ba94fff14ad38ba8d8ecd6a4c78224a7d110c11",
          "md5": "6652e664def0387116615654770bf1c8"
        }
      ]
    }
  ]
}
